[package]
name = "joker-sys"
version = "0.1.0"
#authors = ["noone"]

links = "joker"
build = "build.rs"

[dependencies]
#libc = "0.1"
libc = "*"

[dependencies.cypher-sys]
git = "https://github.com/drasich/cypher.git"

[build-dependencies]
pkg-config = "0.3"
gcc = "0.3"

